services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - PRTF-network

networks:
  PRTF-network:
    driver: bridge
    external: true
